YOUTUBE_PLAYLIST_ITEM = "YOUTUBE_PLAYLIST_ITEM"
YOUTUBE_ITEM = "YOUTUBE_ITEM"
SPOTIFY_PLAYLIST_ITEM = "SPOTIFY_PLAYLIST_ITEM"
YOUTUBE_VIDEO_REGEX = r"^(https?\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$"
YOUTUBE_PLAYLIST_REGEX = r"^https?:\/\/(www.youtube.com|youtube.com)\/playlist(.*)$"
SPOTIFY_ALBUM_REGEX = r"^(https:\/\/open.spotify.com\/album\/)([a-zA-Z0-9]+)(.*)$"
SPOTIFY_PLAYLIST_REGEX = r"^(https:\/\/open.spotify.com\/playlist\/)([a-zA-Z0-9]+)(.*)$"
SPOTIFY_TRACK_REGEX = r"^(https:\/\/open.spotify.com\/track\/)([a-zA-Z0-9]+)(.*)$"
